version: '3'

services:
  wordpress_81:
    image: wordpress
    ports:
      - "81:80"
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    networks:
      - wordpress_network

volumes:
  wordpress_data:

networks:
  wordpress_network:
    # external: true
